### ISSUE TITLE
Feature: Extra Credit - Alchemy API 

### ISSUE THREAD

**Issue by remyroo** [Remsauce/bc-9-twttrmood#5]
As a user I should be able to perform and display sentiment analysis using the Alchemy API

**Comment by andela-anandaa** [comment]
Any updates on this task?

**Comment by remyroo** [comment]
Hi Nandaa, reading the documentation to see how to make it work. Would you have any tips? :)

**Comment by andela-anandaa** [comment]
Seeing this now, glad it was fixed/closed.
