### ISSUE TITLE
Bugs: Fix them!

### ISSUE THREAD

**Issue by remyroo** [Remsauce/bc-9-twttrmood#6]
Fix bugs as they arise. I'll update this with the specific bugs as they arise.

**Comment by remyroo** [comment]
Current bug - twitter api was working, now raising an error when I try to pull data.

**Comment by amwaleh** [comment]
Found fix to this bug !!

**Comment by remyroo** [comment]
Required simplejson to parse the twitter data correctly. Did a pip install then imported it into OAuth.py.

**Comment by andela-anandaa** [comment]
Is good to open an issue as the bugs come. So each bug has it's own unique issue.
